name: Node.js with Gulp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: gulp

  test:
    runs-on: ubuntu-latest
    steps:
      - name: mocha test
        run: mocha