name: NodeJS with Gulp

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        node-version: '16'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build
      run: npm install & gulp
